# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 450)
        Dialog.setMinimumSize(QtCore.QSize(450, 450))
        Dialog.setMaximumSize(QtCore.QSize(450, 450))
        Dialog.setStyleSheet("background-color: black;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 10, 251, 71))
        self.label.setStyleSheet("font: 75 36pt \"Bosch Office Sans\";\n"
"color: rgb(255, 255, 255);\n"
"background: none")
        self.label.setObjectName("label")
        self.mudar = QtWidgets.QPushButton(Dialog)
        self.mudar.setGeometry(QtCore.QRect(160, 220, 181, 71))
        self.mudar.setStyleSheet("background-color: white;\n"
"font: 87 16pt \"Bosch Sans Black\";")
        self.mudar.setObjectName("mudar")
        self.siar = QtWidgets.QPushButton(Dialog)
        self.siar.setGeometry(QtCore.QRect(370, 410, 71, 31))
        self.siar.setStyleSheet("background-color: none;\n"
"")
        self.siar.setObjectName("siar")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(-10, -10, 461, 461))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../Pictures/Wilson.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label.raise_()
        self.mudar.raise_()
        self.siar.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Tela inicial"))
        self.mudar.setText(_translate("Dialog", "Mudar de tela"))
        self.siar.setText(_translate("Dialog", "Sair"))
import img_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
