# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'texto.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 450)
        MainWindow.setMinimumSize(QtCore.QSize(450, 450))
        MainWindow.setMaximumSize(QtCore.QSize(450, 450))
        MainWindow.setStyleSheet("background-color: rgb(255, 217, 80);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputT = QtWidgets.QLineEdit(self.centralwidget)
        self.inputT.setGeometry(QtCore.QRect(30, 340, 191, 71))
        self.inputT.setStyleSheet("background-color: white;\n"
"font: 87 12pt \"Bosch Sans Black\";")
        self.inputT.setText("")
        self.inputT.setObjectName("inputT")
        self.sim = QtWidgets.QLabel(self.centralwidget)
        self.sim.setGeometry(QtCore.QRect(130, 110, 201, 171))
        self.sim.setStyleSheet("background-color: none;\n"
"font: 87 12pt \"Bosch Sans Black\";\n"
"align-text: center")
        self.sim.setText("")
        self.sim.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.sim.setWordWrap(True)
        self.sim.setObjectName("sim")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 290, 181, 41))
        self.label_2.setStyleSheet("background-color: none;\n"
"font: 87 20pt \"Bosch Sans Black\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.okB = QtWidgets.QPushButton(self.centralwidget)
        self.okB.setGeometry(QtCore.QRect(230, 350, 41, 41))
        self.okB.setStyleSheet("background-color: white;\n"
"font: 87 16pt \"Bosch Sans Black\";")
        self.okB.setObjectName("okB")
        self.voltar = QtWidgets.QPushButton(self.centralwidget)
        self.voltar.setGeometry(QtCore.QRect(350, 390, 91, 41))
        self.voltar.setStyleSheet("background-color:red;\n"
"font-color:white;\n"
"font: 12pt \"Bosch Sans\";\n"
"background: none;")
        self.voltar.setObjectName("voltar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 50, 141, 31))
        self.label_3.setStyleSheet("background-color: none;\n"
"font: 16pt \"Bosch Sans\";")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Escreva Aqui"))
        self.okB.setText(_translate("MainWindow", "Ok"))
        self.voltar.setText(_translate("MainWindow", "Voltar"))
        self.label_3.setText(_translate("MainWindow", "Texto Bacana "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
