# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Finish.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 464)
        MainWindow.setMaximumSize(QtCore.QSize(800, 465))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.principal = QtWidgets.QFrame(self.centralwidget)
        self.principal.setGeometry(QtCore.QRect(0, -50, 801, 651))
        self.principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.principal.setObjectName("principal")
        self.lbAki = QtWidgets.QLabel(self.principal)
        self.lbAki.setGeometry(QtCore.QRect(470, 110, 241, 291))
        self.lbAki.setText("")
        self.lbAki.setPixmap(QtGui.QPixmap(":/aki_expressions/aki01.png"))
        self.lbAki.setScaledContents(True)
        self.lbAki.setObjectName("lbAki")
        self.frame = QtWidgets.QFrame(self.principal)
        self.frame.setGeometry(QtCore.QRect(100, 90, 361, 331))
        self.frame.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 40px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 20, 111, 21))
        self.label.setStyleSheet("font: 600 16pt \"Segoe UI\";\n"
"border: none;")
        self.label.setObjectName("label")
        self.lbImg = QtWidgets.QLabel(self.frame)
        self.lbImg.setGeometry(QtCore.QRect(90, 50, 191, 191))
        self.lbImg.setStyleSheet("border-radius: 0;")
        self.lbImg.setText("")
        self.lbImg.setScaledContents(True)
        self.lbImg.setObjectName("lbImg")
        self.lbName = QtWidgets.QLabel(self.frame)
        self.lbName.setGeometry(QtCore.QRect(60, 250, 251, 21))
        self.lbName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbName.setStyleSheet("font: 600 16pt \"Segoe UI\";\n"
"border: none;")
        self.lbName.setText("")
        self.lbName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbName.setObjectName("lbName")
        self.lbSubName = QtWidgets.QLabel(self.frame)
        self.lbSubName.setGeometry(QtCore.QRect(60, 280, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbSubName.setFont(font)
        self.lbSubName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbSubName.setStyleSheet("font: 400 10pt \"Segoe UI\";\n"
"border: none;")
        self.lbSubName.setText("")
        self.lbSubName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSubName.setObjectName("lbSubName")
        self.btnPlayAgn = QtWidgets.QPushButton(self.principal)
        self.btnPlayAgn.setGeometry(QtCore.QRect(200, 430, 161, 41))
        self.btnPlayAgn.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnPlayAgn.setObjectName("btnPlayAgn")
        self.frame_2 = QtWidgets.QFrame(self.principal)
        self.frame_2.setGeometry(QtCore.QRect(490, 130, 20, 20))
        self.frame_2.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.principal)
        self.frame_3.setGeometry(QtCore.QRect(510, 170, 20, 20))
        self.frame_3.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lbRoom = QtWidgets.QLabel(self.principal)
        self.lbRoom.setGeometry(QtCore.QRect(0, 50, 1001, 521))
        self.lbRoom.setText("")
        self.lbRoom.setPixmap(QtGui.QPixmap("room_akinator.jpg"))
        self.lbRoom.setScaledContents(True)
        self.lbRoom.setObjectName("lbRoom")
        self.principal_2 = QtWidgets.QFrame(self.principal)
        self.principal_2.setGeometry(QtCore.QRect(690, 480, 801, 651))
        self.principal_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.principal_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.principal_2.setObjectName("principal_2")
        self.frame_4 = QtWidgets.QFrame(self.principal_2)
        self.frame_4.setGeometry(QtCore.QRect(100, 90, 361, 331))
        self.frame_4.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 40px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(130, 20, 111, 21))
        self.label_2.setStyleSheet("font: 600 16pt \"Segoe UI\";\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.lbImg_2 = QtWidgets.QLabel(self.frame_4)
        self.lbImg_2.setGeometry(QtCore.QRect(90, 50, 191, 191))
        self.lbImg_2.setStyleSheet("border-radius: 0;")
        self.lbImg_2.setText("")
        self.lbImg_2.setObjectName("lbImg_2")
        self.lbName_2 = QtWidgets.QLabel(self.frame_4)
        self.lbName_2.setGeometry(QtCore.QRect(60, 250, 251, 21))
        self.lbName_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbName_2.setStyleSheet("font: 600 16pt \"Segoe UI\";\n"
"border: none;")
        self.lbName_2.setText("")
        self.lbName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbName_2.setObjectName("lbName_2")
        self.lbSubName_2 = QtWidgets.QLabel(self.frame_4)
        self.lbSubName_2.setGeometry(QtCore.QRect(60, 280, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbSubName_2.setFont(font)
        self.lbSubName_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbSubName_2.setStyleSheet("font: 400 10pt \"Segoe UI\";\n"
"border: none;")
        self.lbSubName_2.setText("")
        self.lbSubName_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSubName_2.setObjectName("lbSubName_2")
        self.btnBack_2 = QtWidgets.QPushButton(self.principal_2)
        self.btnBack_2.setGeometry(QtCore.QRect(50, 430, 81, 31))
        self.btnBack_2.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnBack_2.setObjectName("btnBack_2")
        self.frame_5 = QtWidgets.QFrame(self.principal_2)
        self.frame_5.setGeometry(QtCore.QRect(490, 130, 20, 20))
        self.frame_5.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 10px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.principal_2)
        self.frame_6.setGeometry(QtCore.QRect(510, 170, 20, 20))
        self.frame_6.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 10px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lbRoom.raise_()
        self.lbAki.raise_()
        self.frame.raise_()
        self.btnPlayAgn.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.principal_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "I THINK OF"))
        self.btnPlayAgn.setText(_translate("MainWindow", "Play Again"))
        self.lbRoom.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"  align-items: center;\n"
"  background-color: rgb(238, 139, 0);\n"
"  border-radius: 6px;\n"
"  box-shadow: transparent 0 0 0 3px,rgba(18, 18, 18, .1) 0 6px 20px;\n"
"  box-sizing: border-box;\n"
"  color: rgb(255, 255, 255);\n"
"  cursor: pointer;\n"
"  display: inline-flex;\n"
"  flex: 1 1 auto;\n"
"  font-family: Inter,sans-serif;\n"
"  font-size: 1.2rem;\n"
"  font-weight: 700;\n"
"  justify-content: center;\n"
"  line-height: 1;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 1rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: box-shadow .2s,-webkit-box-shadow .2s;\n"
"  white-space: nowrap;\n"
"  border: 0;\n"
"  user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    box-shadow: #121212 0 0 0 3px, transparent 0 0 0 0;\n"
"}"))
        self.label_2.setText(_translate("MainWindow", "I THINK OF"))
        self.btnBack_2.setText(_translate("MainWindow", "Back"))
import imgs_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
