# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 465)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.principal = QtWidgets.QFrame(self.centralwidget)
        self.principal.setGeometry(QtCore.QRect(0, -50, 801, 651))
        self.principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.principal.setObjectName("principal")
        self.lbRoom = QtWidgets.QLabel(self.principal)
        self.lbRoom.setGeometry(QtCore.QRect(0, 50, 1001, 521))
        self.lbRoom.setText("")
        self.lbRoom.setPixmap(QtGui.QPixmap("room_akinator.jpg"))
        self.lbRoom.setScaledContents(True)
        self.lbRoom.setObjectName("lbRoom")
        self.lbAki = QtWidgets.QLabel(self.principal)
        self.lbAki.setGeometry(QtCore.QRect(470, 110, 241, 291))
        self.lbAki.setText("")
        self.lbAki.setPixmap(QtGui.QPixmap(":/aki_expressions/aki01.png"))
        self.lbAki.setScaledContents(True)
        self.lbAki.setObjectName("lbAki")
        self.frame = QtWidgets.QFrame(self.principal)
        self.frame.setGeometry(QtCore.QRect(120, 90, 361, 91))
        self.frame.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 40px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbQuestion = QtWidgets.QLabel(self.frame)
        self.lbQuestion.setGeometry(QtCore.QRect(30, 20, 301, 51))
        self.lbQuestion.setStyleSheet("font: 600 12pt \"Segoe UI\";\n"
"border: none;")
        self.lbQuestion.setText("")
        self.lbQuestion.setObjectName("lbQuestion")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.principal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 200, 321, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.btns_anws = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.btns_anws.setContentsMargins(0, 0, 0, 0)
        self.btns_anws.setObjectName("btns_anws")
        self.btnYes = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnYes.setMinimumSize(QtCore.QSize(100, 35))
        self.btnYes.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnYes.setObjectName("btnYes")
        self.btns_anws.addWidget(self.btnYes)
        self.btnNo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnNo.setMinimumSize(QtCore.QSize(100, 35))
        self.btnNo.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnNo.setObjectName("btnNo")
        self.btns_anws.addWidget(self.btnNo)
        self.btnIdk = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnIdk.setMinimumSize(QtCore.QSize(100, 35))
        self.btnIdk.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnIdk.setObjectName("btnIdk")
        self.btns_anws.addWidget(self.btnIdk)
        self.btnPs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnPs.setMinimumSize(QtCore.QSize(100, 35))
        self.btnPs.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnPs.setObjectName("btnPs")
        self.btns_anws.addWidget(self.btnPs)
        self.btnPn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnPn.setMinimumSize(QtCore.QSize(100, 35))
        self.btnPn.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnPn.setObjectName("btnPn")
        self.btns_anws.addWidget(self.btnPn)
        self.btnBack = QtWidgets.QPushButton(self.principal)
        self.btnBack.setGeometry(QtCore.QRect(50, 430, 81, 31))
        self.btnBack.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 15px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnBack.setObjectName("btnBack")
        self.frame_2 = QtWidgets.QFrame(self.principal)
        self.frame_2.setGeometry(QtCore.QRect(480, 150, 20, 20))
        self.frame_2.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.principal)
        self.frame_3.setGeometry(QtCore.QRect(510, 170, 20, 20))
        self.frame_3.setStyleSheet("background: rgb(255, 255, 255);\n"
"border: 1px solid #000;\n"
"border-radius: 10px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbRoom.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"  align-items: center;\n"
"  background-color: rgb(238, 139, 0);\n"
"  border-radius: 6px;\n"
"  box-shadow: transparent 0 0 0 3px,rgba(18, 18, 18, .1) 0 6px 20px;\n"
"  box-sizing: border-box;\n"
"  color: rgb(255, 255, 255);\n"
"  cursor: pointer;\n"
"  display: inline-flex;\n"
"  flex: 1 1 auto;\n"
"  font-family: Inter,sans-serif;\n"
"  font-size: 1.2rem;\n"
"  font-weight: 700;\n"
"  justify-content: center;\n"
"  line-height: 1;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 1rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: box-shadow .2s,-webkit-box-shadow .2s;\n"
"  white-space: nowrap;\n"
"  border: 0;\n"
"  user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    box-shadow: #121212 0 0 0 3px, transparent 0 0 0 0;\n"
"}"))
        self.btnYes.setText(_translate("MainWindow", "Yes"))
        self.btnNo.setText(_translate("MainWindow", "No"))
        self.btnIdk.setText(_translate("MainWindow", "I Don\'t Know"))
        self.btnPs.setText(_translate("MainWindow", "Probably"))
        self.btnPn.setText(_translate("MainWindow", "Probably Not"))
        self.btnBack.setText(_translate("MainWindow", "Back"))
import imgs_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
