# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Start.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(700, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbRoom = QtWidgets.QLabel(self.centralwidget)
        self.lbRoom.setGeometry(QtCore.QRect(-100, 0, 1101, 571))
        self.lbRoom.setText("")
        self.lbRoom.setPixmap(QtGui.QPixmap("room_akinator.jpg"))
        self.lbRoom.setScaledContents(True)
        self.lbRoom.setObjectName("lbRoom")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(460, 120, 171, 261))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/aki_expressions/aki02.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(140, 100, 291, 271))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(129, 205, 240);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(40, 20, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Minangkabau")
        font.setPointSize(60)
        self.label.setFont(font)
        self.label.setStyleSheet("border:none;\n"
"color: #000;\n"
"text-shadow: -1px 0 black, 0 1px black, 1px 0 black, 0 -1px black;")
        self.label.setObjectName("label")
        self.btnPlayAgn = QtWidgets.QPushButton(self.frame)
        self.btnPlayAgn.setGeometry(QtCore.QRect(50, 130, 191, 61))
        self.btnPlayAgn.setStyleSheet("QPushButton {\n"
"      align-items: center;\n"
"      background-color: #4849EF;\n"
"    border: 1px solid #212151;\n"
"      border-radius: 6px;\n"
"    box-sizing: border-box;\n"
"     color: rgb(255, 255, 255);\n"
"    cursor: pointer;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    font-weight: 700;\n"
"    font-size: 20px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    transition: 1s;\n"
"    background-color:  #181847;\n"
"}")
        self.btnPlayAgn.setObjectName("btnPlayAgn")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(220, 240, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbRoom.setStyleSheet(_translate("MainWindow", "QPushButton {\n"
"  align-items: center;\n"
"  background-color: rgb(238, 139, 0);\n"
"  border-radius: 6px;\n"
"  box-shadow: transparent 0 0 0 3px,rgba(18, 18, 18, .1) 0 6px 20px;\n"
"  box-sizing: border-box;\n"
"  color: rgb(255, 255, 255);\n"
"  cursor: pointer;\n"
"  display: inline-flex;\n"
"  flex: 1 1 auto;\n"
"  font-family: Inter,sans-serif;\n"
"  font-size: 1.2rem;\n"
"  font-weight: 700;\n"
"  justify-content: center;\n"
"  line-height: 1;\n"
"  margin: 0;\n"
"  outline: none;\n"
"  padding: 1rem 1.2rem;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  transition: box-shadow .2s,-webkit-box-shadow .2s;\n"
"  white-space: nowrap;\n"
"  border: 0;\n"
"  user-select: none;\n"
"  touch-action: manipulation;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    box-shadow: #121212 0 0 0 3px, transparent 0 0 0 0;\n"
"}"))
        self.label.setText(_translate("MainWindow", "akinator"))
        self.btnPlayAgn.setText(_translate("MainWindow", "PLAY NOW"))
        self.label_2.setText(_translate("MainWindow", "By: Flepsz"))
import imgs_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
